import json
import re
from datetime import datetime
from mapper import map_to_attack   # Import from the new file

print("🔥 CyberShield - MITRE ATT&CK Mapping Automation Framework")
print("=" * 70)
print("✅ ATT&CK Enterprise Matrix loaded successfully!\n")

def generate_navigator_layer(description: str, layer_name="CyberShield Mapping"):
    """Generate and save Navigator layer"""
    matches = map_to_attack(description)
    
    layer = {
        "name": layer_name,
        "version": "4.5",
        "domain": "enterprise-attack",
        "description": f"Generated by CyberShield on {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "created": datetime.now().isoformat(),
        "modified": datetime.now().isoformat(),
        "techniques": [],
        "gradient": {"colors": ["#ff6666", "#ffe766", "#66ff66"], "minValue": 0, "maxValue": 100},
        "legendItems": [
            {"label": "High Confidence", "color": "#66ff66"},
            {"label": "Medium Confidence", "color": "#ffe766"},
            {"label": "Low Confidence", "color": "#ff6666"}
        ],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#dddddd"
    }
    
    for match in matches:
        normalized = min(100, match['score'] * 2)
        color = "#66ff66" if normalized > 70 else "#ffe766" if normalized > 40 else "#ff6666"
        
        layer["techniques"].append({
            "techniqueID": match['technique_id'],
            "tactic": match['tactic'].lower().replace(" ", "-"),
            "color": color,
            "comment": f"Score: {match['score']} | {description[:120]}...",
            "enabled": True,
            "metadata": [{"name": "Score", "value": str(match['score'])}]
        })
    
    filename = f"cyber_shield_layer_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(filename, "w", encoding="utf-8") as f:
        json.dump(layer, f, indent=2)
    
    print(f"✅ Layer saved: {filename} ({len(matches)} techniques mapped)")
    return filename


# ====================== INTERACTIVE TOOL ======================
if __name__ == "__main__":
    print("Type threat descriptions below. Type 'quit' to exit.\n")
    
    while True:
        user_input = input("Description: ").strip()
        
        if user_input.lower() in ['quit', 'exit', 'q']:
            print("👋 Thank you for using CyberShield!")
            break
        
        if not user_input:
            continue
            
        print(f"\nMapping: \"{user_input}\"")
        print("-" * 60)
        
        results = map_to_attack(user_input)
        for r in results:
            print(f"→ {r['technique_id']} | {r['name']} | {r['tactic']} (Score: {r['score']})")
        
        choice = input("\nGenerate Navigator Layer? (y/n): ").strip().lower()
        if choice == 'y':
            generate_navigator_layer(user_input)
        
        print("\n" + "="*70 + "\n")