from mitreattack.stix20 import MitreAttackData
import json
import re
from datetime import datetime
from collections import OrderedDict

print("🚀 CyberShield - Generating ATT&CK Navigator Layer\n")

# Load ATT&CK data
attack_data = MitreAttackData("enterprise-attack.json")
print("✅ ATT&CK data loaded successfully!\n")

def clean_map_to_attack(description: str, top_n=6):
    """Clean mapper function"""
    if not description:
        return []
    
    desc_lower = description.lower().strip()
    seen = OrderedDict()
    
    all_techs = attack_data.get_techniques() + attack_data.get_subtechniques()
    
    for tech in all_techs:
        tech_id = tech['external_references'][0]['external_id']
        tech_name = tech['name'].lower()
        
        # Skip deprecated techniques
        if tech.get('x_mitre_deprecated', False):
            continue
            
        score = 0
        
        # Strong exact name match
        if re.search(r'\b' + re.escape(tech_name) + r'\b', desc_lower):
            score += 25
        
        # Word matches
        name_words = [w for w in tech_name.split() if len(w) > 3]
        for word in name_words:
            if word in desc_lower:
                score += 7
        
        # High-value keyword boosts
        high_value = {
            'phish': ['T1566'],
            'powershell': ['T1059.001'],
            'lsass': ['T1003.001'],
            'mimikatz': ['T1003.001'],
            'scheduled task': ['T1053.005'],
            'rdp': ['T1021.001'],
            'dns tunnel': ['T1071.004'],
            'lateral': ['T1021'],
            'exfil': ['T1041', 'T1567']
        }
        
        for keyword, good_ids in high_value.items():
            if keyword in desc_lower and any(tech_id.startswith(g) for g in good_ids):
                score += 15
        
        if score >= 12 and tech_id not in seen:
            kill_chain = tech.get('kill_chain_phases', [])
            tactic = kill_chain[0].get('phase_name', 'unknown').replace('-', ' ').title() if kill_chain else 'Unknown'
            
            seen[tech_id] = {
                'technique_id': tech_id,
                'name': tech['name'],
                'tactic': tactic,
                'score': score
            }
    
    return sorted(seen.values(), key=lambda x: x['score'], reverse=True)[:top_n]


def create_navigator_layer(description: str, layer_name="CyberShield Mapping"):
    """Generate ATT&CK Navigator compatible JSON layer"""
    
    matches = clean_map_to_attack(description)
    
    layer = {
        "name": layer_name,
        "version": "4.5",
        "domain": "enterprise-attack",
        "description": f"Auto-generated by CyberShield from: {description[:150]}...",
        "created": datetime.now().isoformat(),
        "modified": datetime.now().isoformat(),
        "techniques": [],
        "gradient": {
            "colors": ["#ff6666", "#ffe766", "#66ff66"],
            "minValue": 0,
            "maxValue": 100
        },
        "legendItems": [
            {"label": "High Confidence", "color": "#66ff66"},
            {"label": "Medium Confidence", "color": "#ffe766"},
            {"label": "Low Confidence", "color": "#ff6666"}
        ],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#dddddd"
    }
    
    for match in matches:
        normalized_score = min(100, match['score'] * 2)
        color = "#66ff66" if normalized_score > 70 else "#ffe766" if normalized_score > 40 else "#ff6666"
        
        layer["techniques"].append({
            "techniqueID": match['technique_id'],
            "tactic": match['tactic'].lower().replace(" ", "-"),
            "color": color,
            "comment": f"Confidence Score: {match['score']} | Detected from input description",
            "enabled": True,
            "metadata": [
                {"name": "Score", "value": str(match['score'])},
                {"name": "Technique", "value": match['name']}
            ]
        })
    
    # Save the layer file
    filename = f"attack_layer_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(filename, "w", encoding="utf-8") as f:
        json.dump(layer, f, indent=2)
    
    print(f"✅ Navigator Layer successfully created!")
    print(f"   Filename : {filename}")
    print(f"   Techniques mapped : {len(layer['techniques'])}")
    print(f"   Layer name : {layer_name}")
    return filename


# ====================== TEST ======================
if __name__ == "__main__":
    test_description = "The attacker sent a phishing email with a malicious attachment to trick the employee and then used PowerShell to download malware"
    
    print("Generating layer for test case...")
    print(f"Input: {test_description}\n")
    
    layer_file = create_navigator_layer(test_description, 
                                      layer_name="CyberShield - Phishing + PowerShell Test")
    
    print("\n🎉 Layer generation complete!")
    print("To view this layer:")
    print("1. Go to: https://mitre-attack.github.io/attack-navigator/")
    print("2. Click 'Open Layer' → 'Upload from file'")
    print(f"3. Select the file: {layer_file}")